version: '3'
services:
  app:
    container_name: omni_app
    build: .
    ports: 
      - 8000:8000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres          
    networks:
      - omni


  postgres:
    image: postgres:latest
    container_name: omni_postgres
    env_file:
      - ./app.env
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - omni

volumes:
  api:
  database:      

# Networks to be created to facilitate communication between containers
networks:
  omni:
    driver: bridge            
